export const ADD_EXPENSE = "ADD_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const SEARCH_EXPENSE = "SEARCH_EXPENSE";
export const ON_EDIT_CLICK = "ON_EDIT_CLICK"
export const EDIT_BUDGET_AMOUNT = "EDIT_BUDGET_AMOUNT";
