export const ON_DELETE_POKEMON = "ON_DELETE_POKEMON";
export const SAVED_FETCHED_POKEMON = "SAVED_FETCHED_POKEMON";
export const SET_COPYLIST_AFTER_SEARCH = "SET_COPY_AFTER_SEARCH";
export const ON_SAVE_POKEMON = "ON_SAVE_POKEMON";
export const SET_SEARCH_OBJECT = "SET_SEARCH_OBJECT";
export const SET_SELECTED_POKEMON = "SET_SELECTED_POKEMON";
